#!/usr/bin/env php
<?php
function dd($value) {
    var_dump($value);
    die();
}
function d($value) {
    var_dump($value);
}

//autoload classfile
function __autoload($classname) {
    $path = explode('\\', $classname);

    $realPath = '';
    foreach ($path as $value) {
        $realPath .= '/' . $value;
    }
    require_once __DIR__ . $realPath . '.php';
}

$console = new \Core\Console($argv[1]);

$console->cliHanddle($argv);

$supportPlugins = $console->getSupportPlugin();

$plugin = new \Core\Plugin();

?>
