#!/usr/bin/env php
<?php
function dd($value) {
    var_dump($value);
    die();
}
function d($value) {
    var_dump($value);
}

define('__APPDIR__', __DIR__);

require_once __APPDIR__ . '/Core/Autoload.php';

//autoload classfile
spl_autoload_register(array('\\Core\\AutoLoad', 'loadClassLoader'));

$console = new \Core\Console($argv[1]);

$console->cliHanddle($argv);

$supportPlugins = $console->getSupportPlugin();
foreach($supportPlugins as $value) {
    $plugin = new \Core\Plugin($value);
    $plugin->console($argv);
}

?>
